"""数据源抽象接口。

新增数据源时，只需实现 StockProvider 和/或 NewsProvider Protocol，
然后在 __init__.py 中注册即可。"""

from typing import Optional, Protocol, runtime_checkable

import pandas as pd


@runtime_checkable
class StockProvider(Protocol):
    """股票数据源接口。"""

    def is_available(self) -> bool: ...
    def get_stock_list(self) -> list[dict]: ...
    def get_stock_basic_info(self, code: str) -> Optional[dict]: ...
    def get_stock_quotes(self, code: str) -> Optional[dict]: ...
    def get_batch_stock_quotes(self, codes: list[str]) -> dict[str, dict]: ...
    def get_historical_data(
        self, code: str, start_date: str, end_date: str, period: str = "daily"
    ) -> Optional[pd.DataFrame]: ...
    def get_financial_data(self, code: str) -> dict: ...
    def get_market_status(self) -> dict: ...


@runtime_checkable
class NewsProvider(Protocol):
    """新闻数据源接口。"""

    def collect_market_news(self) -> list[dict]: ...
    def get_stock_news(self, symbol: str, limit: int = 10) -> list[dict]: ...
